### ISSUE TITLE
Argument is too large: value (line 2022, file Code, project console)

### ISSUE THREAD

**Issue by SergeyShevelev** [tyskdm/rajah#1]
Trying to use ```gas-console``` as a reporter I've been getting this error.
When I use a ```addConsoleReporter()``` and make output to the Logger service this error doesn't appear.
The error happens with any release of the used library "console" even with no this library used at all.
The gas-console is empty.
However the sample project is still working and it is reporting to gas-console.

**Comment by tyskdm** [comment]
Hi, sorry for late response.

In `line 2022, file Code, project console`, there's this code:
```js
  this.cache.put(this.name, str, 15*60); // 15min.
```
The Cache service limits the size of value(in this case `str` = output to console) to 100KB.
I'm sorry but 'gas-console' doesn't care about this limitation.
Was your report larger than that?
if (no) pls let me know.
